language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - doxygen
      - g++-7

before_install:
  - export CXX=/usr/bin/g++-7

script:
  - cmake . -B".build" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .build --target all
  - cmake --build .build --target test
  - cmake --build .build --target doc

deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir:    .build/docs/html
  on:
    branch:     master

notifications:
  email:
    on-success: never
    on-failure: never
