language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - doxygen
      - libboost-all-dev
      - g++-7
      - gcc-7

before_install:
  - export CXX=/usr/bin/g++-7
  - export CC=/usr/bin/gcc-7

script:
  - cmake . -B"$HOME/.build" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug
  - cmake --build $HOME/.build --target all
  - cmake --build $HOME/.build --target test
  - cmake --build $HOME/.build --target doc

deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir:    $HOME/.build/docs/html
  on:
    branch:     master

notifications:
  email:
    on-success: never
    on-failure: never
