language: cpp
sudo: required

addons:
  apt:
    packages:
      - cmake
      - doxygen
      - libboost-all-dev

before_install:
  - sudo add-apt-repository ppa:jonathonf/gcc-7.1 -y
  - sudo apt-get update -q
  - sudo apt-get install -y gcc-7 g++-7

compiler:
  - g++

script:
  - cmake cmake -G"Unix Makefiles" -B"./.build" -H"./" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .build --target all
  - cmake --build .build --target doc

deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir:    ./.build/html
  on:
    branch:     master
