language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - doxygen
      - g++-7
      - gcc-7

before_install:
  - pip install --user cpp-coveralls
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7

script:
  - cmake . -B".build" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=1
  - cmake --build .build --target all
  - cmake --build .build --target doc
  - cd .build && ctest -VV

after_success:
  - coveralls --root .build -exclude ".*googletest-.*" -exclude ".*CMakeFiles.*"

deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir:    .build/docs/html
  on:
    branch:     master

notifications:
  email:
    on-success: never
    on-failure: never
