language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - doxygen
      - libboost-all-dev
      - libgtest-dev
      - g++-7

compiler:
  - g++-7

script:
  - cmake -B".build" -H"./" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .build --target all
  - cmake --build .build --target test
  - cmake --build .build --target doc

deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir:    $HOME/.build/docs/html
  on:
    branch:     master

notifications:
  email:
    on-success: never
    on-failure: never
